export interface Stock {
  code: string;
  name: string;
  sector: string;
  index: string;
}

export const BIST_STOCKS: Stock[] = [
  { code: "THYAO", name: "Türk Hava Yolları", sector: "Ulaştırma", index: "BIST 30" },
  { code: "GARAN", name: "Garanti BBVA", sector: "Bankacılık", index: "BIST 30" },
  { code: "ISCTR", name: "İş Bankası C", sector: "Bankacılık", index: "BIST 30" },
  { code: "AKBNK", name: "Akbank", sector: "Bankacılık", index: "BIST 30" },
  { code: "YKBNK", name: "Yapı Kredi Bankası", sector: "Bankacılık", index: "BIST 30" },
  { code: "ARCLK", name: "Arçelik", sector: "Dayanıklı Tüketim", index: "BIST 30" },
  { code: "ASELS", name: "Aselsan", sector: "Teknoloji", index: "BIST 30" },
  { code: "SISE", name: "Şişe Cam", sector: "İnşaat", index: "BIST 30" },
  { code: "EREGL", name: "Ereğli Demir Çelik", sector: "Metal", index: "BIST 30" },
  { code: "KRDMD", name: "Kardemir D", sector: "Metal", index: "BIST 30" },
  { code: "KCHOL", name: "Koç Holding", sector: "Holding", index: "BIST 30" },
  { code: "SAHOL", name: "Sabancı Holding", sector: "Holding", index: "BIST 30" },
  { code: "TUPRS", name: "Tüpraş", sector: "Enerji", index: "BIST 30" },
  { code: "BIMAS", name: "BİM Mağazalar", sector: "Perakende", index: "BIST 30" },
  { code: "PGSUS", name: "Pegasus", sector: "Ulaştırma", index: "BIST 30" },
  { code: "TOASO", name: "Tofaş", sector: "Otomotiv", index: "BIST 30" },
  { code: "EKGYO", name: "Emlak Konut GYO", sector: "Gayrimenkul", index: "BIST 30" },
  { code: "KONTR", name: "Kontrolmatik", sector: "Teknoloji", index: "BIST 30" },
  { code: "ASTOR", name: "Astor Enerji", sector: "Enerji", index: "BIST 30" },
  { code: "GUBRF", name: "Gübre Fabrikaları", sector: "Kimya", index: "BIST 30" },
  { code: "ALARK", name: "Alarko Holding", sector: "Holding", index: "BIST 50" },
  { code: "TAVHL", name: "TAV Havalimanları", sector: "Ulaştırma", index: "BIST 50" },
  { code: "OTKAR", name: "Otokar", sector: "Otomotiv", index: "BIST 50" },
  { code: "HEKTS", name: "Hektaş", sector: "Kimya", index: "BIST 50" },
  { code: "SASA", name: "Sasa Polyester", sector: "Tekstil", index: "BIST 50" },
  { code: "PETKM", name: "Petkim", sector: "Kimya", index: "BIST 50" },
  { code: "VESTL", name: "Vestel", sector: "Dayanıklı Tüketim", index: "BIST 50" },
  { code: "KOZAA", name: "Koza Altın", sector: "Madencilik", index: "BIST 50" },
  { code: "KZBGY", name: "Kuzu GYO", sector: "Gayrimenkul", index: "BIST 50" },
  { code: "ENKAI", name: "Enka İnşaat", sector: "İnşaat", index: "BIST 50" },
  { code: "DOHOL", name: "Doğan Holding", sector: "Holding", index: "BIST 50" },
  { code: "SKBNK", name: "Şekerbank", sector: "Bankacılık", index: "BIST 50" },
  { code: "HALKB", name: "Halkbank", sector: "Bankacılık", index: "BIST 50" },
  { code: "VAKBN", name: "Vakıfbank", sector: "Bankacılık", index: "BIST 50" },
  { code: "TSKB", name: "T. Sınai Kalkınma Bankası", sector: "Bankacılık", index: "BIST 50" },
  { code: "GSDHO", name: "GSD Holding", sector: "Holding", index: "BIST 50" },
  { code: "SNGYO", name: "Sinpaş GYO", sector: "Gayrimenkul", index: "BIST 50" },
  { code: "ISGYO", name: "İş GYO", sector: "Gayrimenkul", index: "BIST 50" },
  { code: "AKFGY", name: "Akfen GYO", sector: "Gayrimenkul", index: "BIST 50" },
  { code: "AGHOL", name: "Anadolu Grubu Holding", sector: "Holding", index: "BIST 100" },
  { code: "CCOLA", name: "Coca-Cola İçecek", sector: "Gıda", index: "BIST 100" },
  { code: "ULUUN", name: "Ulusoy Un", sector: "Gıda", index: "BIST 100" },
  { code: "BRISA", name: "Brisa", sector: "Otomotiv", index: "BIST 100" },
  { code: "FROTO", name: "Ford Otosan", sector: "Otomotiv", index: "BIST 100" },
  { code: "MAVI", name: "Mavi Giyim", sector: "Tekstil", index: "BIST 100" },
  { code: "KMPUR", name: "Kimpur", sector: "Kimya", index: "BIST 100" },
  { code: "GUSGR", name: "Güneş Sigorta", sector: "Sigorta", index: "BIST 100" },
  { code: "ANSGR", name: "Anadolu Sigorta", sector: "Sigorta", index: "BIST 100" },
  { code: "TTRAK", name: "Türk Traktör", sector: "Tarım", index: "BIST 100" },
  { code: "CANTE", name: "Can2 Termik", sector: "Enerji", index: "BIST 100" },
  { code: "KONYA", name: "Konya Çimento", sector: "İnşaat", index: "BIST 100" },
  { code: "NUHCM", name: "Nuh Çimento", sector: "İnşaat", index: "BIST 100" },
  { code: "BOBET", name: "Bobet", sector: "Tekstil", index: "BIST 100" },
  { code: "DESA", name: "Desa Deri", sector: "Tekstil", index: "BIST 100" },
  { code: "DERIM", name: "Derimod", sector: "Tekstil", index: "BIST 100" },
  { code: "ITTFH", name: "İttifak Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "TATGD", name: "Tat Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "ULKER", name: "Ülker Bisküvi", sector: "Gıda", index: "BIST TÜM" },
  { code: "BANVT", name: "Banvit", sector: "Gıda", index: "BIST TÜM" },
  { code: "TUKAS", name: "Tukaş", sector: "Gıda", index: "BIST TÜM" },
  { code: "KERVT", name: "Kerevitaş", sector: "Gıda", index: "BIST TÜM" },
  { code: "AVOD", name: "Avrupa Yakası", sector: "Gıda", index: "BIST TÜM" },
  { code: "BAKAB", name: "Bak Ambalaj", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "DGGYO", name: "Doğuş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "RYGYO", name: "Reyal GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "VRGYO", name: "Vakıf GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "HLGYO", name: "Halil İbrahim GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "EDIP", name: "Edip İnşaat", sector: "İnşaat", index: "BIST TÜM" },
  { code: "IEYHO", name: "İstanbul Enternasyonal", sector: "Holding", index: "BIST TÜM" },
  { code: "PRKME", name: "Park Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "AKSEN", name: "Akenerji", sector: "Enerji", index: "BIST 50" },
  { code: "ZOREN", name: "Zorlu Enerji", sector: "Enerji", index: "BIST 50" },
  { code: "ODAS", name: "Odaş Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "MAGEN", name: "Magen Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "BMSTL", name: "BMS Teknoloji", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "NETAS", name: "Netaş", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "KFEIN", name: "Kafein Yazılım", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "LOGO", name: "Logo Yazılım", sector: "Teknoloji", index: "BIST 100" },
  { code: "OBASE", name: "Obase", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "MOBTL", name: "Mobiltel", sector: "İletişim", index: "BIST TÜM" },
  { code: "TCELL", name: "Turkcell", sector: "İletişim", index: "BIST 30" },
  { code: "TTKOM", name: "Türk Telekom", sector: "İletişim", index: "BIST 50" },
  { code: "KRONT", name: "Kron Telekom", sector: "İletişim", index: "BIST TÜM" },
  { code: "QUAGR", name: "Qua Granite", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BUCIM", name: "Büyükçekmece Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BTCIM", name: "Batıçim", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BSOKE", name: "Bursa Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "OYAKC", name: "Oyak Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "AFYON", name: "Afyon Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "YBTAS", name: "Yibitas", sector: "İnşaat", index: "BIST TÜM" },
  { code: "DGKLB", name: "Doğanlar Mobilya", sector: "Mobilya", index: "BIST TÜM" },
  { code: "TEZOL", name: "Tezol", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "SAMAT", name: "Samat", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "PAKPN", name: "Pakpen", sector: "İnşaat", index: "BIST TÜM" },
  { code: "SERVE", name: "Servest", sector: "Hizmet", index: "BIST TÜM" },
  { code: "AKYHO", name: "Akdeniz Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "AVGYO", name: "Avrupa GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ATAGY", name: "Ata GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AGYO", name: "Anadolu GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AKMGY", name: "Akmerkez GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "DZGYO", name: "Deniz GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ISGYO", name: "İş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "KLGYO", name: "Kiler GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "HLVKS", name: "Halil Vatandaş", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MIPAZ", name: "Mimtaş Pazarlama", sector: "Ticaret", index: "BIST TÜM" },
  { code: "AKGRT", name: "Ak Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "MARTI", name: "Martı", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "SAYAS", name: "Say Yenilenebilir", sector: "Enerji", index: "BIST TÜM" },
  { code: "AKFYE", name: "Akfen Yenilenebilir", sector: "Enerji", index: "BIST TÜM" },
  { code: "CWENE", name: "CW Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "NTGAZ", name: "Naturel Gaz", sector: "Enerji", index: "BIST TÜM" },
  { code: "ESCAR", name: "Escar", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "DOAS", name: "Doğuş Otomotiv", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "OTTO", name: "Otto", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "TMSN", name: "Tümosan", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "MAKS", name: "Makina Takım", sector: "Makine", index: "BIST TÜM" },
  { code: "SARKY", name: "Sarkuysan", sector: "Metal", index: "BIST TÜM" },
  { code: "KCAER", name: "Kocaer Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "HURGZ", name: "Hürriyet Gazetecilik", sector: "Medya", index: "BIST TÜM" },
  { code: "BLCYT", name: "Bilici Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "CLEBI", name: "Çelebi Hava Servisi", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "PNSUT", name: "Pınar Süt", sector: "Gıda", index: "BIST TÜM" },
  { code: "SELGD", name: "Selçuk Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "BRSAN", name: "Borusan", sector: "Metal", index: "BIST TÜM" },
  { code: "ISKPL", name: "İskur Plastik", sector: "Plastik", index: "BIST TÜM" },
  { code: "EGEEN", name: "Ege Endüstri", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "BOSSA", name: "Bossa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "YUNSA", name: "Yünsa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KORDS", name: "Kordsa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "IPEKE", name: "İpek Doğal Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "BRYAT", name: "Borusan Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "TUPRB", name: "Tüpraş B", sector: "Enerji", index: "BIST TÜM" },
  { code: "DERHL", name: "Der Halı", sector: "Tekstil", index: "BIST TÜM" },
  { code: "GENTS", name: "Gentaş", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ATSYH", name: "Atlantik Sigorta", sector: "Sigorta", index: "BIST TÜM" },
  { code: "AKSGY", name: "Akis GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "CMBTN", name: "Çimbeton", sector: "İnşaat", index: "BIST TÜM" },
  { code: "DMRGD", name: "Demirgökçü", sector: "Tekstil", index: "BIST TÜM" },
  { code: "IZMDC", name: "İzmir Demir Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "IZFAS", name: "İzmir Fuar", sector: "Hizmet", index: "BIST TÜM" },
  { code: "KAPLM", name: "Kaplaminc", sector: "İnşaat", index: "BIST TÜM" },
  { code: "OYLUM", name: "Oylum Sınai", sector: "İnşaat", index: "BIST TÜM" },
  { code: "PARSN", name: "Parsan", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "PNSUT", name: "Pınar Süt", sector: "Gıda", index: "BIST TÜM" },
  { code: "SARKY", name: "Sarkuysan", sector: "Metal", index: "BIST TÜM" },
  { code: "SELEC", name: "Selçuk Ecza", sector: "Sağlık", index: "BIST TÜM" },
  { code: "SNKRN", name: "Sönmez Kordon", sector: "Tekstil", index: "BIST TÜM" },
  { code: "SUNTK", name: "Sunteks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "TETMT", name: "Tetamatsan", sector: "Tekstil", index: "BIST TÜM" },
  { code: "TIRE", name: "Tire Kutsan", sector: "Tekstil", index: "BIST TÜM" },
  { code: "TRILC", name: "Trilogic", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "TUCLK", name: "Tülcük", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ULUUN", name: "Ulusoy Un", sector: "Gıda", index: "BIST TÜM" },
  { code: "VKGYO", name: "Vakıf GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "YATAS", name: "Yataş", sector: "Mobilya", index: "BIST TÜM" },
  { code: "YYAPI", name: "Yüzyapı", sector: "İnşaat", index: "BIST TÜM" },
  { code: "ZOREN", name: "Zorlu Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ALKIM", name: "Alkim Kimya", sector: "Kimya", index: "BIST TÜM" },
  { code: "AYGAZ", name: "Aygaz", sector: "Enerji", index: "BIST TÜM" },
  { code: "DESPC", name: "Despec", sector: "Ticaret", index: "BIST TÜM" },
  { code: "EKSUN", name: "Eksun Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "ELITE", name: "Elite Naturel", sector: "Gıda", index: "BIST TÜM" },
  { code: "ERBOS", name: "Erbosan", sector: "İnşaat", index: "BIST TÜM" },
  { code: "GEDZA", name: "Gediz Ambalaj", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "GLBMD", name: "Global Makina", sector: "Makine", index: "BIST TÜM" },
  { code: "GLRYH", name: "Güler Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GRSEL", name: "Gürsel", sector: "İnşaat", index: "BIST TÜM" },
  { code: "HUBVC", name: "Hub Girişim", sector: "Yatırım", index: "BIST TÜM" },
  { code: "IHAAS", name: "İhaaş", sector: "Ticaret", index: "BIST TÜM" },
  { code: "JANTS", name: "Jantsa", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "KAPLM", name: "Kaplaminc", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KARTN", name: "Kartonpiyer", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KONKA", name: "Konka", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KRSTL", name: "Kristal Kola", sector: "Gıda", index: "BIST TÜM" },
  { code: "MEDTR", name: "Meditera", sector: "Sağlık", index: "BIST TÜM" },
  { code: "MEGAP", name: "Megapol Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "MERKO", name: "Merko Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "METUR", name: "Metemtur", sector: "Turizm", index: "BIST TÜM" },
  { code: "MIPAZ", name: "Mimtaş Pazarlama", sector: "Ticaret", index: "BIST TÜM" },
  { code: "NIBAS", name: "Niğbaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "ONCSM", name: "Öncü Sağlık", sector: "Sağlık", index: "BIST TÜM" },
  { code: "ORGE", name: "Örge Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "OSMEN", name: "Osmanlı Menkul", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OZGYO", name: "Ozon GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "OZKGY", name: "Özak GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PAPIL", name: "Papilon", sector: "Tekstil", index: "BIST TÜM" },
  { code: "PETUN", name: "Petun", sector: "Gıda", index: "BIST TÜM" },
  { code: "PKART", name: "Plastikkart", sector: "Plastik", index: "BIST TÜM" },
  { code: "PNLSN", name: "Paneksan", sector: "Plastik", index: "BIST TÜM" },
  { code: "POLHO", name: "Polisan Holding", sector: "Kimya", index: "BIST TÜM" },
  { code: "PRDGS", name: "Pardus Girişim", sector: "Yatırım", index: "BIST TÜM" },
  { code: "PRKAB", name: "Park Elektrik B", sector: "Enerji", index: "BIST TÜM" },
  { code: "PSDTC", name: "Pimaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "RNPOL", name: "RN Polimer", sector: "Plastik", index: "BIST TÜM" },
  { code: "RODRG", name: "Roderick", sector: "İnşaat", index: "BIST TÜM" },
  { code: "RTALB", name: "Royal Halı", sector: "Tekstil", index: "BIST TÜM" },
  { code: "RYGYO", name: "Reyal GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "SANEL", name: "Sanel", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "SEGMN", name: "Seğmen Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "SKTAS", name: "Şektaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "SMRTG", name: "Smart Güneş", sector: "Enerji", index: "BIST TÜM" },
  { code: "SODSN", name: "Soda Sanayi", sector: "Kimya", index: "BIST TÜM" },
  { code: "TDGYO", name: "Trend GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "TKFEN", name: "Tekfen Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "TKURU", name: "Taze Kuru", sector: "Gıda", index: "BIST TÜM" },
  { code: "TMSN", name: "Tümosan", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "TRNSK", name: "Transpek", sector: "Plastik", index: "BIST TÜM" },
  { code: "TUKAS", name: "Tukaş", sector: "Gıda", index: "BIST TÜM" },
  { code: "TURGG", name: "Türkiye Garanti", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "ULAS", name: "Ulaşlar Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "ULUFA", name: "Ulufa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "VAKKO", name: "Vakko", sector: "Tekstil", index: "BIST TÜM" },
  { code: "VERTU", name: "Verusat", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "VKING", name: "Viking Kağıt", sector: "Kağıt", index: "BIST TÜM" },
  { code: "YAPRK", name: "Yaprak", sector: "Gıda", index: "BIST TÜM" },
  { code: "YAYLA", name: "Yayla Agro", sector: "Gıda", index: "BIST TÜM" },
  { code: "YGGYO", name: "Yeni Gimat GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "YKSLN", name: "Yükselen Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "YONGA", name: "Yonga Mobilya", sector: "Mobilya", index: "BIST TÜM" },
  { code: "ZEDUR", name: "Zedur Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ZEREN", name: "Zeren Tekstil", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ZRGYO", name: "Ziraat GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ADEL", name: "Adel", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ADGYO", name: "Adra GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AEFES", name: "Anadolu Efes", sector: "Gıda", index: "BIST TÜM" },
  { code: "AFYON", name: "Afyon Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "AGES", name: "Agesa", sector: "Sigorta", index: "BIST TÜM" },
  { code: "AGHOL", name: "Anadolu Grubu", sector: "Holding", index: "BIST TÜM" },
  { code: "AKCNS", name: "Akçansa", sector: "İnşaat", index: "BIST TÜM" },
  { code: "AKGRT", name: "Ak Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "AKMGY", name: "Akmerkez GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AKSA", name: "Aksa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "AKSUE", name: "Aksu Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ALBRK", name: "Albaraka Türk", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "ALCAR", name: "Alarko Carrier", sector: "Dayanıklı Tüketim", index: "BIST TÜM" },
  { code: "ALCTL", name: "Alcatel", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ALKA", name: "Alka", sector: "Kimya", index: "BIST TÜM" },
  { code: "ALKIM", name: "Alkim Kimya", sector: "Kimya", index: "BIST TÜM" },
  { code: "ALYAG", name: "Alyağ", sector: "Enerji", index: "BIST TÜM" },
  { code: "ANELE", name: "Anel Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "ANHYT", name: "Anadolu Hayat", sector: "Sigorta", index: "BIST TÜM" },
  { code: "ANSGR", name: "Anadolu Sigorta", sector: "Sigorta", index: "BIST TÜM" },
  { code: "ARASE", name: "Arase", sector: "Ticaret", index: "BIST TÜM" },
  { code: "ARENA", name: "Arena", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ARMDA", name: "Armağan", sector: "Ticaret", index: "BIST TÜM" },
  { code: "ARSAN", name: "Arsan", sector: "İnşaat", index: "BIST TÜM" },
  { code: "ARTMS", name: "Artemis", sector: "Gıda", index: "BIST TÜM" },
  { code: "ARZUM", name: "Arzum", sector: "Dayanıklı Tüketim", index: "BIST TÜM" },
  { code: "ASELS", name: "Aselsan", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ASUZU", name: "Asuzu", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "ATATP", name: "Ata Toprak", sector: "Tarım", index: "BIST TÜM" },
  { code: "ATLAS", name: "Atlas Menkul", sector: "Yatırım", index: "BIST TÜM" },
  { code: "AVHOL", name: "Avrupa Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "AVOD", name: "Avrupa Yakası", sector: "Gıda", index: "BIST TÜM" },
  { code: "AYCES", name: "Ayçaş", sector: "Tarım", index: "BIST TÜM" },
  { code: "AYEN", name: "Ayen Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "AYGAZ", name: "Aygaz", sector: "Enerji", index: "BIST TÜM" },
  { code: "BAGFS", name: "Bağfas", sector: "Kimya", index: "BIST TÜM" },
  { code: "BAKAB", name: "Bak Ambalaj", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "BALAT", name: "Balatacılar", sector: "Ticaret", index: "BIST TÜM" },
  { code: "BANVT", name: "Banvit", sector: "Gıda", index: "BIST TÜM" },
  { code: "BERA", name: "Bera Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "BEYAZ", name: "Beyaz Filo", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "BFREN", name: "Bosch Fren", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "BJKAS", name: "Beşiktaş", sector: "Spor", index: "BIST TÜM" },
  { code: "BLCYT", name: "Bilici Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "BNTAS", name: "Bantaş", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "BOSSA", name: "Bossa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "BRISA", name: "Brisa", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "BRKO", name: "Birko", sector: "Tekstil", index: "BIST TÜM" },
  { code: "BRKVY", name: "Bereket Varlık", sector: "Yatırım", index: "BIST TÜM" },
  { code: "BRLSM", name: "Birleşim Mühendislik", sector: "Mühendislik", index: "BIST TÜM" },
  { code: "BRMEN", name: "Birmen", sector: "Tekstil", index: "BIST TÜM" },
  { code: "BRSAN", name: "Borusan", sector: "Metal", index: "BIST TÜM" },
  { code: "BRYAT", name: "Borusan Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "BSOKE", name: "Bursa Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BTCIM", name: "Batıçim", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BUCIM", name: "Büyükçekmece Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BURCE", name: "Burçelik", sector: "Metal", index: "BIST TÜM" },
  { code: "BURVA", name: "Bursa Veteriner", sector: "Sağlık", index: "BIST TÜM" },
  { code: "BYDNR", name: "Boydak", sector: "Tekstil", index: "BIST TÜM" },
  { code: "CASA", name: "Casa", sector: "Gıda", index: "BIST TÜM" },
  { code: "CATES", name: "Çates", sector: "İnşaat", index: "BIST TÜM" },
  { code: "CEMAS", name: "Çemaş", sector: "Madencilik", index: "BIST TÜM" },
  { code: "CEMTS", name: "Çemtaş", sector: "Metal", index: "BIST TÜM" },
  { code: "CLEBI", name: "Çelebi", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "CMBTN", name: "Çimbeton", sector: "İnşaat", index: "BIST TÜM" },
  { code: "COSMO", name: "Cosmos Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "CRDFA", name: "Creditwest Faktoring", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "DAGI", name: "Dağları", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DAPGM", name: "Dap GMYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "DARDL", name: "Dardanel", sector: "Gıda", index: "BIST TÜM" },
  { code: "DERHL", name: "Der Halı", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DESA", name: "Desa Deri", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DESPC", name: "Despec", sector: "Ticaret", index: "BIST TÜM" },
  { code: "DEVA", name: "Deva Holding", sector: "İlaç", index: "BIST TÜM" },
  { code: "DGATE", name: "Datagate", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "DGGYO", name: "Doğuş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "DIRIT", name: "Diriteks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DITAS", name: "Ditaş", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "DMSAS", name: "Demisaş", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "DNISI", name: "Denizli İşletme", sector: "Yatırım", index: "BIST TÜM" },
  { code: "DOBUR", name: "Doğan Burda", sector: "Medya", index: "BIST TÜM" },
  { code: "DOCO", name: "Do & Co", sector: "Gıda", index: "BIST TÜM" },
  { code: "DOFER", name: "Doğaner", sector: "Turizm", index: "BIST TÜM" },
  { code: "DOGUB", name: "Doğuş Boru", sector: "Metal", index: "BIST TÜM" },
  { code: "DOKTA", name: "Doktaş", sector: "Mobilya", index: "BIST TÜM" },
  { code: "DURDO", name: "Durdur", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DYOBY", name: "Dyo Boya", sector: "Kimya", index: "BIST TÜM" },
  { code: "ECILC", name: "Eczacıbaşı İlaç", sector: "İlaç", index: "BIST TÜM" },
  { code: "ECZYT", name: "Eczacıbaşı Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "EGEPO", name: "Ege Profil", sector: "Metal", index: "BIST TÜM" },
  { code: "EGGUB", name: "Ege Gübre", sector: "Kimya", index: "BIST TÜM" },
  { code: "EGPRO", name: "Ege Profil", sector: "Metal", index: "BIST TÜM" },
  { code: "EGSER", name: "Ege Seramik", sector: "İnşaat", index: "BIST TÜM" },
  { code: "EKSUN", name: "Eksun Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "ELITE", name: "Elite Naturel", sector: "Gıda", index: "BIST TÜM" },
  { code: "EMKEL", name: "Emek Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "ENJSA", name: "Enerjisa", sector: "Enerji", index: "BIST TÜM" },
  { code: "ERBOS", name: "Erbosan", sector: "İnşaat", index: "BIST TÜM" },
  { code: "ERSU", name: "Ersu", sector: "Gıda", index: "BIST TÜM" },
  { code: "ETYAT", name: "Ethem Sancak", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "FADE", name: "Fade", sector: "Tekstil", index: "BIST TÜM" },
  { code: "FENER", name: "Fenerbahçe", sector: "Spor", index: "BIST TÜM" },
  { code: "FLAP", name: "Flap Kongre", sector: "Hizmet", index: "BIST TÜM" },
  { code: "FMIZP", name: "Favori Dinlenme", sector: "Hizmet", index: "BIST TÜM" },
  { code: "FONET", name: "Fonet", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "FORMT", name: "Formet", sector: "Metal", index: "BIST TÜM" },
  { code: "FRIGO", name: "Frigo Pak", sector: "Gıda", index: "BIST TÜM" },
  { code: "FROTO", name: "Ford Otosan", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "GARAN", name: "Garanti BBVA", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "GEDIK", name: "Gedik Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GENTS", name: "Gentaş", sector: "Tekstil", index: "BIST TÜM" },
  { code: "GEREL", name: "Gersan Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "GLDTR", name: "Global Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GLRYH", name: "Güler Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GLYHO", name: "Gülaylar", sector: "Perakende", index: "BIST TÜM" },
  { code: "GSDDE", name: "GSD Denizcilik", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "GSDHO", name: "GSD Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "GUBRF", name: "Gübre Fabrikaları", sector: "Kimya", index: "BIST TÜM" },
  { code: "GUSGR", name: "Güneş Sigorta", sector: "Sigorta", index: "BIST TÜM" },
  { code: "Halkb", name: "Halkbank", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "HATEK", name: "Hateks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "HDFGS", name: "Hadımköy", sector: "Gıda", index: "BIST TÜM" },
  { code: "HEKTS", name: "Hektaş", sector: "Kimya", index: "BIST TÜM" },
  { code: "HLGYO", name: "Halil İbrahim GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "HUBVC", name: "Hub Girişim", sector: "Yatırım", index: "BIST TÜM" },
  { code: "HURGZ", name: "Hürriyet", sector: "Medya", index: "BIST TÜM" },
  { code: "ICBCT", name: "ICBC Turkey", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "IDGYO", name: "İdealist GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "IEYHO", name: "İstanbul Enternasyonal", sector: "Yatırım", index: "BIST TÜM" },
  { code: "IHAAS", name: "İhaaş", sector: "Ticaret", index: "BIST TÜM" },
  { code: "IHGZT", name: "İhlas Gazetecilik", sector: "Medya", index: "BIST TÜM" },
  { code: "IHYAY", name: "İhlas Yayın", sector: "Medya", index: "BIST TÜM" },
  { code: "INDES", name: "İndeks Bilgisayar", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "INFO", name: "İnfo Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "INTEM", name: "İntema", sector: "Mobilya", index: "BIST TÜM" },
  { code: "IPEKE", name: "İpek Doğal Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ISBIR", name: "İşbir Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "ISDMR", name: "İskenderun Demir", sector: "Metal", index: "BIST TÜM" },
  { code: "ISFIN", name: "İş Finansal", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "ISGYO", name: "İş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ISMEN", name: "İş Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "ISSEN", name: "İstikbal", sector: "Mobilya", index: "BIST TÜM" },
  { code: "IZFAS", name: "İzmir Fuar", sector: "Hizmet", index: "BIST TÜM" },
  { code: "JANTS", name: "Jantsa", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "KAPLM", name: "Kaplaminc", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KARTN", name: "Kartonpiyer", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KARSN", name: "Karsan", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "KATMR", name: "Katmer", sector: "Gıda", index: "BIST TÜM" },
  { code: "KCHOL", name: "Koç Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "KENT", name: "Kent Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "KERVN", name: "Kervansaray", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KERVT", name: "Kerevitaş", sector: "Gıda", index: "BIST TÜM" },
  { code: "KFEIN", name: "Kafein Yazılım", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "KLGYO", name: "Kiler GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "KLMSN", name: "Klimasan", sector: "Dayanıklı Tüketim", index: "BIST TÜM" },
  { code: "KMPUR", name: "Kimpur", sector: "Kimya", index: "BIST TÜM" },
  { code: "KNFRT", name: "Konfrut", sector: "Gıda", index: "BIST TÜM" },
  { code: "KONTR", name: "Kontrolmatik", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "KONYA", name: "Konya Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KORDS", name: "Kordsa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KOZAA", name: "Koza Altın", sector: "Madencilik", index: "BIST TÜM" },
  { code: "KOZAL", name: "Koza Madencilik", sector: "Madencilik", index: "BIST TÜM" },
  { code: "KRDMA", name: "Kardemir A", sector: "Metal", index: "BIST TÜM" },
  { code: "KRDMB", name: "Kardemir B", sector: "Metal", index: "BIST TÜM" },
  { code: "KRDMD", name: "Kardemir D", sector: "Metal", index: "BIST TÜM" },
  { code: "KRONT", name: "Kron", sector: "İletişim", index: "BIST TÜM" },
  { code: "KRPET", name: "Körfez Petrol", sector: "Enerji", index: "BIST TÜM" },
  { code: "KRSAN", name: "Karsu", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KRVGD", name: "Kervan Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "KSTUR", name: "Kuşadası Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "KTSKR", name: "Kutsoykar", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KUTPO", name: "Kutuptaşı", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KUYAS", name: "Kuyumcukent", sector: "Perakende", index: "BIST TÜM" },
  { code: "LIDFA", name: "Lider Faktoring", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "LINK", name: "Link Bilgisayar", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "LKMNH", name: "Lokman Hekim", sector: "Sağlık", index: "BIST TÜM" },
  { code: "LOGO", name: "Logo Yazılım", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "LRSHO", name: "Larsen", sector: "Ticaret", index: "BIST TÜM" },
  { code: "LUKSK", name: "Lüks Kadife", sector: "Tekstil", index: "BIST TÜM" },
  { code: "LYDHO", name: "Lider Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "MAALT", name: "Marmaris Altın", sector: "Perakende", index: "BIST TÜM" },
  { code: "MAKIM", name: "Makim", sector: "Makine", index: "BIST TÜM" },
  { code: "MAKTK", name: "Makteknik", sector: "Makine", index: "BIST TÜM" },
  { code: "MANAS", name: "Manas", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "MARKA", name: "Marka Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "MARTI", name: "Martı", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "MAVI", name: "Mavi Giyim", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MCPER", name: "MC Perakende", sector: "Perakende", index: "BIST TÜM" },
  { code: "MEMSA", name: "Memsa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MEPET", name: "Mepet", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "MERIT", name: "Merit Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "METRO", name: "Metro Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "MGROS", name: "Migros", sector: "Perakende", index: "BIST TÜM" },
  { code: "MIPAZ", name: "Mimtaş Pazarlama", sector: "Ticaret", index: "BIST TÜM" },
  { code: "MPARK", name: "Marmara Park", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "NATEN", name: "Naturel Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "NIBAS", name: "Niğbaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "NTGAZ", name: "Naturel Gaz", sector: "Enerji", index: "BIST TÜM" },
  { code: "NUGYO", name: "Nurol GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ODAS", name: "Odaş", sector: "Enerji", index: "BIST TÜM" },
  { code: "ONCSM", name: "Öncü Sağlık", sector: "Sağlık", index: "BIST TÜM" },
  { code: "ORGE", name: "Örge Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "OSMEN", name: "Osmanlı Menkul", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OSTIM", name: "Ostim", sector: "Holding", index: "BIST TÜM" },
  { code: "OTKAR", name: "Otokar", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "OTTO", name: "Otto", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "OYAKC", name: "Oyak Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "OYAYO", name: "Oya Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OYYAT", name: "Oyak Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OZATD", name: "Özata", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "OZGYO", name: "Ozon GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "OZKGY", name: "Özak GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "OZRDN", name: "Özerden", sector: "Plastik", index: "BIST TÜM" },
  { code: "OZSUB", name: "Özsubat", sector: "Tarım", index: "BIST TÜM" },
  { code: "PAGYO", name: "Panorama GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PARSN", name: "Parsan", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "PASEU", name: "Pasha EU", sector: "Yatırım", index: "BIST TÜM" },
  { code: "PATEK", name: "Patek", sector: "Tekstil", index: "BIST TÜM" },
  { code: "PCILT", name: "Pınar Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "PEGYO", name: "Pera GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PEKGY", name: "Pekintaş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PETKM", name: "Petkim", sector: "Kimya", index: "BIST TÜM" },
  { code: "PETUN", name: "Petun", sector: "Gıda", index: "BIST TÜM" },
  { code: "PGSUS", name: "Pegasus", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "PINSU", name: "Pınar Su", sector: "Gıda", index: "BIST TÜM" },
  { code: "PKART", name: "Plastikkart", sector: "Plastik", index: "BIST TÜM" },
  { code: "PNLSN", name: "Paneksan", sector: "Plastik", index: "BIST TÜM" },
  { code: "PNSUT", name: "Pınar Süt", sector: "Gıda", index: "BIST TÜM" },
  { code: "POLHO", name: "Polisan Holding", sector: "Kimya", index: "BIST TÜM" },
  { code: "POLTK", name: "Politek", sector: "Kimya", index: "BIST TÜM" },
  { code: "PRDGS", name: "Pardus Girişim", sector: "Yatırım", index: "BIST TÜM" },
  { code: "PRZMA", name: "Prizma", sector: "Tekstil", index: "BIST TÜM" },
  { code: "PSDTC", name: "Pimaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "QNBTR", name: "QNB Finansbank", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "RALYH", name: "Ralph", sector: "Yatırım", index: "BIST TÜM" },
  { code: "RAYSG", name: "Ray Sigorta", sector: "Sigorta", index: "BIST TÜM" },
  { code: "REEDR", name: "Reeder", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "RGYAS", name: "Reysaş", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "RNPOL", name: "RN Polimer", sector: "Plastik", index: "BIST TÜM" },
  { code: "RODRG", name: "Roderick", sector: "İnşaat", index: "BIST TÜM" },
  { code: "RTALB", name: "Royal Halı", sector: "Tekstil", index: "BIST TÜM" },
  { code: "RUBNS", name: "Rubenis", sector: "Ticaret", index: "BIST TÜM" },
  { code: "RYGYO", name: "Reyal GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "SAHOL", name: "Sabancı Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "SANEL", name: "Sanel", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "SARKY", name: "Sarkuysan", sector: "Metal", index: "BIST TÜM" },
  { code: "SASA", name: "Sasa Polyester", sector: "Tekstil", index: "BIST TÜM" },
  { code: "SAYAS", name: "Say Yenilenebilir", sector: "Enerji", index: "BIST TÜM" },
  { code: "SELEC", name: "Selçuk Ecza", sector: "Sağlık", index: "BIST TÜM" },
  { code: "SELVA", name: "Selva Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "SEYKM", name: "Seyitler", sector: "Madencilik", index: "BIST TÜM" },
  { code: "SILVR", name: "Silver", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "SKBNK", name: "Şekerbank", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "SKTAS", name: "Şektaş", sector: "İnşaat", index: "BIST TÜM" },
  { code: "SMART", name: "Smartiks", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "SMRTG", name: "Smart Güneş", sector: "Enerji", index: "BIST TÜM" },
  { code: "SODSN", name: "Soda Sanayi", sector: "Kimya", index: "BIST TÜM" },
  { code: "SNGYO", name: "Sinpaş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "SUWEN", name: "Suwen", sector: "Tekstil", index: "BIST TÜM" },
  { code: "TATGD", name: "Tat Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "TAVHL", name: "TAV Havalimanları", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "TBORG", name: "T. Boru", sector: "Metal", index: "BIST TÜM" },
  { code: "TCELL", name: "Turkcell", sector: "İletişim", index: "BIST TÜM" },
  { code: "TDGYO", name: "Trend GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "TEKTU", name: "Tektug", sector: "İnşaat", index: "BIST TÜM" },
  { code: "TERA", name: "Tera", sector: "Yatırım", index: "BIST TÜM" },
  { code: "TGSAS", name: "TGS Dış Ticaret", sector: "Ticaret", index: "BIST TÜM" },
  { code: "THYAO", name: "Türk Hava Yolları", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "TKFEN", name: "Tekfen Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "TMSN", name: "Tümosan", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "TOASO", name: "Tofaş", sector: "Otomotiv", index: "BIST TÜM" },
  { code: "TRCAS", name: "Trcas", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "TRILC", name: "Trilogic", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "TRNSK", name: "Transpek", sector: "Plastik", index: "BIST TÜM" },
  { code: "TSKB", name: "T. Sınai Kalkınma Bankası", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "TTKOM", name: "Türk Telekom", sector: "İletişim", index: "BIST TÜM" },
  { code: "TTRAK", name: "Türk Traktör", sector: "Tarım", index: "BIST TÜM" },
  { code: "TUKAS", name: "Tukaş", sector: "Gıda", index: "BIST TÜM" },
  { code: "TUPRS", name: "Tüpraş", sector: "Enerji", index: "BIST TÜM" },
  { code: "TURGG", name: "Türkiye Garanti", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "ULAS", name: "Ulaşlar Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "ULKER", name: "Ülker Bisküvi", sector: "Gıda", index: "BIST TÜM" },
  { code: "VAKBN", name: "Vakıfbank", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "VAKKO", name: "Vakko", sector: "Tekstil", index: "BIST TÜM" },
  { code: "VERUS", name: "Verusa", sector: "Holding", index: "BIST TÜM" },
  { code: "VESTL", name: "Vestel", sector: "Dayanıklı Tüketim", index: "BIST TÜM" },
  { code: "VKING", name: "Viking Kağıt", sector: "Kağıt", index: "BIST TÜM" },
  { code: "YAPRK", name: "Yaprak", sector: "Gıda", index: "BIST TÜM" },
  { code: "YATAS", name: "Yataş", sector: "Mobilya", index: "BIST TÜM" },
  { code: "YAYLA", name: "Yayla Agro", sector: "Gıda", index: "BIST TÜM" },
  { code: "YGGYO", name: "Yeni Gimat GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "YKBNK", name: "Yapı Kredi", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "YKSLN", name: "Yükselen Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "YONGA", name: "Yonga Mobilya", sector: "Mobilya", index: "BIST TÜM" },
  { code: "ZEDUR", name: "Zedur Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ZOREN", name: "Zorlu Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "ZRGYO", name: "Ziraat GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "DGNMO", name: "Doğan Mobilya", sector: "Mobilya", index: "BIST TÜM" },
  { code: "HOROZ", name: "Horoz Lojistik", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "HATEK", name: "Hateks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ANELE", name: "Anel Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "DUNYH", name: "Dünya Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "PLTUR", name: "Polat Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "PKART", name: "Plastikkart", sector: "Plastik", index: "BIST TÜM" },
  { code: "SVGYO", name: "Sevgi GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "TURGG", name: "Türkiye Garanti", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "DOHOL", name: "Doğan Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "KENT", name: "Kent Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "HUBVC", name: "Hub Girişim", sector: "Yatırım", index: "BIST TÜM" },
  { code: "HLVKS", name: "Halil Vatandaş", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ATEKS", name: "Ateks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ATLAS", name: "Atlas Menkul", sector: "Yatırım", index: "BIST TÜM" },
  { code: "BALAT", name: "Balatacılar", sector: "Ticaret", index: "BIST TÜM" },
  { code: "DAGI", name: "Dağları", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DIRIT", name: "Diriteks", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DOFER", name: "Doğaner", sector: "Turizm", index: "BIST TÜM" },
  { code: "EKSUN", name: "Eksun Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "ELITE", name: "Elite Naturel", sector: "Gıda", index: "BIST TÜM" },
  { code: "EMKEL", name: "Emek Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "FMIZP", name: "Favori Dinlenme", sector: "Hizmet", index: "BIST TÜM" },
  { code: "GEREL", name: "Gersan Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "GLBMD", name: "Global Makina", sector: "Makine", index: "BIST TÜM" },
  { code: "GLYHO", name: "Gülaylar", sector: "Perakende", index: "BIST TÜM" },
  { code: "GRSEL", name: "Gürsel", sector: "İnşaat", index: "BIST TÜM" },
  { code: "IHAAS", name: "İhaaş", sector: "Ticaret", index: "BIST TÜM" },
  { code: "INDES", name: "İndeks Bilgisayar", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ITTFH", name: "İttifak Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "KAPLM", name: "Kaplaminc", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KARTN", name: "Kartonpiyer", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KONKA", name: "Konka", sector: "İnşaat", index: "BIST TÜM" },
  { code: "KRPET", name: "Körfez Petrol", sector: "Enerji", index: "BIST TÜM" },
  { code: "KRSAN", name: "Karsu", sector: "Tekstil", index: "BIST TÜM" },
  { code: "KSTUR", name: "Kuşadası Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "KTSKR", name: "Kutsoykar", sector: "Tekstil", index: "BIST TÜM" },
  { code: "LUKSK", name: "Lüks Kadife", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MAKIM", name: "Makim", sector: "Makine", index: "BIST TÜM" },
  { code: "MAKTK", name: "Makteknik", sector: "Makine", index: "BIST TÜM" },
  { code: "MANAS", name: "Manas", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "MCARD", name: "Mcard", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "MEDTR", name: "Meditera", sector: "Sağlık", index: "BIST TÜM" },
  { code: "MEGAP", name: "Megapol Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "MEGMT", name: "Megamet", sector: "İnşaat", index: "BIST TÜM" },
  { code: "MEKAG", name: "Mekanik A.Ş.", sector: "Makine", index: "BIST TÜM" },
  { code: "MEPET", name: "Mepet", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "MERKO", name: "Merko Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "METRO", name: "Metro Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "METUR", name: "Metemtur", sector: "Turizm", index: "BIST TÜM" },
  { code: "MIATK", name: "Mia Teknoloji", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "MNDRS", name: "Menderes Tekstil", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MPARK", name: "Marmara Park", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "NATEN", name: "Naturel Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "NUGYO", name: "Nurol GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "OSTIM", name: "Ostim", sector: "Holding", index: "BIST TÜM" },
  { code: "OYAYO", name: "Oya Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OYYAT", name: "Oyak Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "OZATD", name: "Özata", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "OZRDN", name: "Özerden", sector: "Plastik", index: "BIST TÜM" },
  { code: "OZSUB", name: "Özsubat", sector: "Tarım", index: "BIST TÜM" },
  { code: "OZYSR", name: "Özyeğin Sınai", sector: "Holding", index: "BIST TÜM" },
  { code: "PAGYO", name: "Panorama GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PAMEL", name: "Pamukkale", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "PATEK", name: "Patek", sector: "Tekstil", index: "BIST TÜM" },
  { code: "PCILT", name: "Pınar Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "PEGYO", name: "Pera GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PEKGY", name: "Pekintaş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PINSU", name: "Pınar Su", sector: "Gıda", index: "BIST TÜM" },
  { code: "PRKAB", name: "Park Elektrik", sector: "Enerji", index: "BIST TÜM" },
  { code: "PRZMA", name: "Prizma", sector: "Tekstil", index: "BIST TÜM" },
  { code: "QNBTR", name: "QNB Finansbank", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "RALYH", name: "Ralph Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "REEDR", name: "Reeder", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "RGYAS", name: "Reysaş", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "RUBNS", name: "Rubenis", sector: "Ticaret", index: "BIST TÜM" },
  { code: "SAYAS", name: "Say Yenilenebilir", sector: "Enerji", index: "BIST TÜM" },
  { code: "SEGMN", name: "Seğmen Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "SKYLP", name: "Skyalp", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "SKYMD", name: "Sky Medya", sector: "Medya", index: "BIST TÜM" },
  { code: "SUWEN", name: "Suwen", sector: "Tekstil", index: "BIST TÜM" },
  { code: "TBORG", name: "T. Boru", sector: "Metal", index: "BIST TÜM" },
  { code: "TEKTU", name: "Tektug", sector: "İnşaat", index: "BIST TÜM" },
  { code: "TERA", name: "Tera", sector: "Yatırım", index: "BIST TÜM" },
  { code: "TGSAS", name: "TGS Dış Ticaret", sector: "Ticaret", index: "BIST TÜM" },
  { code: "TRCAS", name: "Trcas", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "TUCLK", name: "Tülcük", sector: "Tekstil", index: "BIST TÜM" },
  { code: "VERTU", name: "Vertu", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "VLONY", name: "Vlon Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "WEBNK", name: "Webnak", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "YEOTK", name: "Yeşilova", sector: "Madencilik", index: "BIST TÜM" },
  { code: "YIGIT", name: "Yiğit Akü", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "YYLGD", name: "Yaylagül", sector: "Gıda", index: "BIST TÜM" },
  { code: "ZEREN", name: "Zeren Tekstil", sector: "Tekstil", index: "BIST TÜM" },
  { code: "ECILC", name: "Eczacıbaşı İlaç", sector: "İlaç", index: "BIST TÜM" },
  { code: "ERSU", name: "Ersu", sector: "Gıda", index: "BIST TÜM" },
  { code: "NATEN", name: "Naturel Enerji", sector: "Enerji", index: "BIST TÜM" },
  { code: "KONTR", name: "Kontrolmatik", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ESEN", name: "Esenboğa", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "GLRMK", name: "Güler Makina", sector: "Makine", index: "BIST TÜM" },
  { code: "BJKAS", name: "Beşiktaş", sector: "Spor", index: "BIST TÜM" },
  { code: "IDGYO", name: "İdealist GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AKFGY", name: "Akfen GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "AKFYE", name: "Akfen Yenilenebilir", sector: "Enerji", index: "BIST TÜM" },
  { code: "ALCTL", name: "Alcatel", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "ARMDA", name: "Armağan", sector: "Ticaret", index: "BIST TÜM" },
  { code: "ATAGY", name: "Ata GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "ATATP", name: "Ata Toprak", sector: "Tarım", index: "BIST TÜM" },
  { code: "AVGYO", name: "Avrupa GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "BNTAS", name: "Bantaş", sector: "Ambalaj", index: "BIST TÜM" },
  { code: "BRMEN", name: "Birmen", sector: "Tekstil", index: "BIST TÜM" },
  { code: "BUCIM", name: "Büyükçekmece Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "BULGS", name: "Bülent Güçlü", sector: "İnşaat", index: "BIST TÜM" },
  { code: "CANTE", name: "Can2 Termik", sector: "Enerji", index: "BIST TÜM" },
  { code: "CATES", name: "Çates", sector: "İnşaat", index: "BIST TÜM" },
  { code: "CELHA", name: "Çelik Halat", sector: "Metal", index: "BIST TÜM" },
  { code: "COSMO", name: "Cosmos Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "CRDFA", name: "Creditwest Faktoring", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "DAGI", name: "Dağları", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DARDL", name: "Dardanel", sector: "Gıda", index: "BIST TÜM" },
  { code: "DESPC", name: "Despec", sector: "Ticaret", index: "BIST TÜM" },
  { code: "DEVA", name: "Deva Holding", sector: "İlaç", index: "BIST TÜM" },
  { code: "DGATE", name: "Datagate", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "DMSAS", name: "Demisaş", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "DOBUR", name: "Doğan Burda", sector: "Medya", index: "BIST TÜM" },
  { code: "DOKTA", name: "Doktaş", sector: "Mobilya", index: "BIST TÜM" },
  { code: "DURDO", name: "Durdur", sector: "Tekstil", index: "BIST TÜM" },
  { code: "DYOBY", name: "Dyo Boya", sector: "Kimya", index: "BIST TÜM" },
  { code: "ECZYT", name: "Eczacıbaşı Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "EGGUB", name: "Ege Gübre", sector: "Kimya", index: "BIST TÜM" },
  { code: "EGPRO", name: "Ege Profil", sector: "Metal", index: "BIST TÜM" },
  { code: "EGSER", name: "Ege Seramik", sector: "İnşaat", index: "BIST TÜM" },
  { code: "ENJSA", name: "Enerjisa", sector: "Enerji", index: "BIST TÜM" },
  { code: "ETYAT", name: "Ethem Sancak", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "FENER", name: "Fenerbahçe", sector: "Spor", index: "BIST TÜM" },
  { code: "FLAP", name: "Flap Kongre", sector: "Hizmet", index: "BIST TÜM" },
  { code: "FONET", name: "Fonet", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "FORMT", name: "Formet", sector: "Metal", index: "BIST TÜM" },
  { code: "FRIGO", name: "Frigo Pak", sector: "Gıda", index: "BIST TÜM" },
  { code: "GEDIK", name: "Gedik Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GLDTR", name: "Global Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "GSDDE", name: "GSD Denizcilik", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "HDFGS", name: "Hadımköy", sector: "Gıda", index: "BIST TÜM" },
  { code: "ICBCT", name: "ICBC Turkey", sector: "Bankacılık", index: "BIST TÜM" },
  { code: "IHGZT", name: "İhlas Gazetecilik", sector: "Medya", index: "BIST TÜM" },
  { code: "IHYAY", name: "İhlas Yayın", sector: "Medya", index: "BIST TÜM" },
  { code: "INTEM", name: "İntema", sector: "Mobilya", index: "BIST TÜM" },
  { code: "ISBIR", name: "İşbir Holding", sector: "Holding", index: "BIST TÜM" },
  { code: "ISDMR", name: "İskenderun Demir", sector: "Metal", index: "BIST TÜM" },
  { code: "ISFIN", name: "İş Finansal", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "ISMEN", name: "İş Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "ISSEN", name: "İstikbal", sector: "Mobilya", index: "BIST TÜM" },
  { code: "IZMDC", name: "İzmir Demir Çelik", sector: "Metal", index: "BIST TÜM" },
  { code: "KLMSN", name: "Klimasan", sector: "Dayanıklı Tüketim", index: "BIST TÜM" },
  { code: "KNFRT", name: "Konfrut", sector: "Gıda", index: "BIST TÜM" },
  { code: "KRVGD", name: "Kervan Gıda", sector: "Gıda", index: "BIST TÜM" },
  { code: "KUYAS", name: "Kuyumcukent", sector: "Perakende", index: "BIST TÜM" },
  { code: "LIDFA", name: "Lider Faktoring", sector: "Finansal Hizmetler", index: "BIST TÜM" },
  { code: "LRSHO", name: "Larsen", sector: "Ticaret", index: "BIST TÜM" },
  { code: "LYDHO", name: "Lider Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "MAALT", name: "Marmaris Altın", sector: "Perakende", index: "BIST TÜM" },
  { code: "MARMR", name: "Marmara", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "MCPER", name: "MC Perakende", sector: "Perakende", index: "BIST TÜM" },
  { code: "MEMSA", name: "Memsa", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MERIT", name: "Merit Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "MIATK", name: "Mia Teknoloji", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "MNDRS", name: "Menderes Tekstil", sector: "Tekstil", index: "BIST TÜM" },
  { code: "MNDTR", name: "Menderes Turizm", sector: "Turizm", index: "BIST TÜM" },
  { code: "NUHCM", name: "Nuh Çimento", sector: "İnşaat", index: "BIST TÜM" },
  { code: "OYLUM", name: "Oylum Sınai", sector: "İnşaat", index: "BIST TÜM" },
  { code: "OZGYO", name: "Ozon GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "OZKGY", name: "Özak GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PAMEL", name: "Pamukkale", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "PEGYO", name: "Pera GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PEKGY", name: "Pekintaş GYO", sector: "Gayrimenkul", index: "BIST TÜM" },
  { code: "PKART", name: "Plastikkart", sector: "Plastik", index: "BIST TÜM" },
  { code: "PNLSN", name: "Paneksan", sector: "Plastik", index: "BIST TÜM" },
  { code: "POLTK", name: "Politek", sector: "Kimya", index: "BIST TÜM" },
  { code: "RODRG", name: "Roderick", sector: "İnşaat", index: "BIST TÜM" },
  { code: "SKYLP", name: "Skyalp", sector: "Ulaştırma", index: "BIST TÜM" },
  { code: "SKYMD", name: "Sky Medya", sector: "Medya", index: "BIST TÜM" },
  { code: "SMRVA", name: "Smartiva", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "SNICA", name: "Sınai", sector: "Holding", index: "BIST TÜM" },
  { code: "SNPAM", name: "Sınai pamuk", sector: "Tekstil", index: "BIST TÜM" },
  { code: "VERTU", name: "Vertu", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "VLONY", name: "Vlon Yatırım", sector: "Yatırım", index: "BIST TÜM" },
  { code: "WEBNK", name: "Webnak", sector: "Teknoloji", index: "BIST TÜM" },
  { code: "YEOTK", name: "Yeşilova", sector: "Madencilik", index: "BIST TÜM" },
  { code: "YIGIT", name: "Yiğit Akü", sector: "Otomotiv Yan Sanayi", index: "BIST TÜM" },
  { code: "YYLGD", name: "Yaylagül", sector: "Gıda", index: "BIST TÜM" }
];

export const getStockByCode = (code: string): Stock | undefined => {
  return BIST_STOCKS.find(s => s.code === code.toUpperCase());
};

export const getStocksBySector = (sector: string): Stock[] => {
  return BIST_STOCKS.filter(s => s.sector === sector);
};

export const getStocksByIndex = (index: string): Stock[] => {
  return BIST_STOCKS.filter(s => s.index === index);
};

export const getAllSectors = (): string[] => {
  return [...new Set(BIST_STOCKS.map(s => s.sector))].sort();
};

export const TOTAL_STOCKS = BIST_STOCKS.length;
